[tts.fish-tts]
voice_profile_path = "voice/fish/powdur_voice.npy"
transcript = "I still need to find myself. Yeah, okay. I need to find myself is some excuse to go have a hoe phase. Find myself? What the"

[tts.qwen3-tts]
ref_audio = "voice/qwen3/ref.wav"
ref_text = "I still need to find myself. Yeah, okay. I need to find myself is some"
instruction = "excited, energetic, animated, with rising intonation"
